site_name: Project X

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes

theme:
  name: material
  icon:
    logo: material/library-outline
  palette: 
    scheme: ayu
  font:
    text: Nunito
    code: Source Code Pro
#  favicon: images/logo.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.expand


extra_css:
- stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gihanx
      name: github
      
#  generator: false


nav:

- HOME: index.md

- HOUDINI:
  - Learning: houdini/houdini.md
  - Assets: houdini/assets.md

- UNREAL:
  - Learning: unreal/unreal.md

- BLENDER:
  - Learning: blender/3d.md

- WINDOWS:
  - programs: windows/programs.md
  - tweaks: windows/tweaks.md

- EXTRA:
  - a: resources.md
  - b: quicksave.md
  - c: extra.md

- LINUX:
  - linux: linux/testss.md