site_name: ""

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

    logo: ""
  palette: 
    scheme: ayu
    primary: black
    accent: light blue
  font:
    text: Nunito
    code: Source Code Pro
#  favicon: images/logo.png

  features:
  #  - navigation.tabs
  #  - navigation.tabs.sticky
     - navigation.instant
  #  - navigation.top
  #  - navigation.expand


extra_css:
- stylesheets/extra.css

extra:
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/gihanx
#      name: github
      
  generator: false

plugins: []

nav:

- BOOKMARK: index.md

- HOUDINI:
  - Learning: houdini/learn.md
  - Assets: houdini/assets.md
  - KineFX: houdini/kinefx.md
  - VAT: houdini/vat.md
  - UI: houdini/houdini.md
  - Vex: houdini/vex.md

- UNREAL:
  - Learning: unreal/unreal.md
  - Install: unreal/ueinstall.md
  - Datamine: unreal/datamine.md

- BLENDER:
  - Learning: blender/blender.md
  - Plugins: blender/plugin.md

- SOFTWARE:
  - Programs: software/programs.md
  - Discord: software/discord.md
  - Steam: software/steam.md
  - Tweaks: software/tweaks.md
  - HyperV: software/hyperv.md
  - Server2022: software/srv22-install.md

- EXTRA:
  - Quicksave: extra/quicksave.md

- LINUX:
  - Linux: linux/linux.md
  - Arch Install: linux/arch-install.md
  - Ubuntu Server Install: linux/ubuntu-server-install.md
  - Tun2Socks: linux/tun2socks.md
  - Git/Github: linux/git.md
  - NeoVim: linux/neovim.md