site_name: Project X

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes

theme:
  name: material
  icon:
    logo: material/library-outline
  palette: 
    scheme: ayu
  font:
    text: Nunito
    code: Source Code Pro
  favicon: images/logo.png

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top

extra_css:
- stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gihanx
      name: github
      
  generator: false


nav:

- Home: index.md

- HOUDINI:
  - Learning: houdini/houdini.md
  - Assets: houdini/houdini.md
  - Fixes: houdini/houdini.md

- UNREAL:
  - Learning: unreal/unreal.md
  - Assets: unreal/unreal.md
  - Fixes: unreal/unreal.md

- BLENDER:
  - Learning: blender/3d.md
  - Assets: blender/3d.md
  - Fixes: blender/3d.md

- WINDOWS:
  - programs: windows/programs.md
  - tweaks: windows/tweaks.md

- LINUX:
  - linux: linux/testss.md

- dev: wip.md