site_name: Personal Doc

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes

theme:
  name: material
  icon:
    logo: material/library-outline
  palette: 
    scheme: ayu
  font:
    text: Nunito
    code: Source Code Pro
#  favicon: images/logo.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.expand


extra_css:
- stylesheets/extra.css

extra:
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/gihanx
#      name: github
      
  generator: false


nav:

- HOME: index.md

- HOUDINI:
  - Learning: houdini/learn.md
  - Assets: houdini/assets.md
  - KineFX: houdini/kinefx.md
  - VAT: houdini/vat.md
  - UI: houdini/houdini.md

- UNREAL:
  - Learning: unreal/unreal.md
  - Install: unreal/ueinstall.md

- BLENDER:
  - Learning: blender/blender.md
  - Plugins: blender/plugin.md

- SOFTWARE:
  - programs: software/programs.md
  - discord: software/discord.md
  - steam: software/steam.md
  - tweaks: software/tweaks.md

- EXTRA:
  - resources: extra/resources.md
  - quicksave: extra/quicksave.md
  - extra: extra/extra.md

- LINUX:
  - linux: linux/linux.md
  - Arch Install: linux/arch-install.md
  - Ubuntu Server Install: linux/ubuntu-server-install.md
  - Tun2Socks: linux/tun2socks.md
  - Git/Github: linux/git.md
  - NeoVim: linux/neovim.md